<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AdminSeeder extends Seeder
{

    public function run()
    {

        DB::table('admins')->insert(
            [
                [
                    'created_by' => 'admin',
                    'name' =>  'Michelle Natasya Subairi',
                    'nim' =>  '2540123795',
                    'email' => 'michelle.natasya12@gmail.com',
                    'position_id' => 1,
                    'position' => 'Project Manager',
                    'department_id' => 'SC',
                    'department' => 'Steering Committee',
                    'division_id' => 'PM',
                    'division' => 'Project Manager',
                    'password' => Hash::make("AEO.PM2540123795")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Geren Widiarta',
                    'nim' =>  '2540125030',
                    'email' => 'gerenwidiarta477@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'MITR',
                    'department' => 'MIT & Registration',
                    'division_id' => 'MIT',
                    'division' => 'Media Information and Technology',
                    'password' => Hash::make("AEO.MIT2540125030")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Jose Stephen Satrya',
                    'nim' =>  '2540124551',
                    'email' => 'jose.satrya@gmail.com',
                    'position_id' => 2,
                    'position' => 'Director',
                    'department_id' => 'MITR',
                    'department' => 'MIT & Registration',
                    'division_id' => 'MIT',
                    'division' => 'MIT & Registration',
                    'password' => Hash::make("AEO.MITR2540124551")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Nicholas Frederick Oongwidjaja',
                    'nim' =>  '2501987192',
                    'email' => 'nicholas22oongwidjaja@gmail.com',
                    'position_id' => 1,
                    'position' => 'Vice Project Manager of Marketing',
                    'department_id' => 'SC',
                    'department' => 'Steering Committee',
                    'division_id' => 'VPMM',
                    'division' => 'Vice Project Manager of Marketing',
                    'password' => Hash::make("AEO.VPMM2501987192")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Stephany Angela Putri Langi',
                    'nim' =>  '2501999545',
                    'email' => 'langiwurangian@gmail.com',
                    'position_id' => 1,
                    'position' => 'Vice Project Manager of Operations',
                    'department_id' => 'SC',
                    'department' => 'Steering Committee',
                    'division_id' => 'VPMO',
                    'division' => 'Vice Project Manager of Operations',
                    'password' => Hash::make("AEO.VPMO2501999545")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Rahmadira Febi Herdiningtyas',
                    'nim' =>  '2540131456',
                    'email' => 'rahmadirafebih@gmail.com',
                    'position_id' => 1,
                    'position' => 'Secretary and Treasurer',
                    'department_id' => 'SC',
                    'department' => 'Steering Committee',
                    'division_id' => 'SCT',
                    'division' => 'Secretary and Treasurer',
                    'password' => Hash::make("AEO.SCT2540131456")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Fanes Hanestan',
                    'nim' =>  '2502000193',
                    'email' => 'fanestan271203@gmail.com',
                    'position_id' => 2,
                    'position' => 'Director',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'CP',
                    'division' => 'Competition',
                    'password' => Hash::make("AEO.CP2502000193"),
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Joey Soesilo',
                    'nim' =>  '2540120351',
                    'email' => 'jsoesilo28@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'OC',
                    'division' => 'Online Competition',
                    'password' => Hash::make("AEO.OC2540120351"),
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Timotius Rosevalt',
                    'nim' =>  '2501961294',
                    'email' => 'timotiusrosevalt@gmail.com',
                    'position_id' => 2,
                    'position' => 'Director',
                    'department_id' => 'EV',
                    'department' => 'Event',
                    'division_id' => 'EV',
                    'division' => 'Event',
                    'password' => Hash::make("AEO.EV2501961294"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Gracia Nurmala',
                    'nim' =>  '2502050153',
                    'email' => 'graciaans@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'EV',
                    'department' => 'Event',
                    'division_id' => 'ME',
                    'division' => 'Main Event',
                    'password' => Hash::make("AEO.ME2502050153"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Kalvin Eryadi',
                    'nim' =>  '2540119734',
                    'email' => 'kalvineryadi12@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'EV',
                    'department' => 'Event',
                    'division_id' => 'PE',
                    'division' => 'Party Event',
                    'password' => Hash::make("AEO.PE2540119734"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Liesa Aprilianty',
                    'nim' =>  '2540124330',
                    'email' => 'liesaprilianty@gmail.com',
                    'position_id' => 2,
                    'position' => 'Director',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'LG',
                    'division' => 'Logistic',
                    'password' => Hash::make("AEO.LG2540124330"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Selma Andjani Mahanum',
                    'nim' =>  '2502011083',
                    'email' => 'andjani.sm@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'ORD',
                    'division' => 'Officer Recruitment and Development',
                    'password' => Hash::make("AEO.ORD2502011083"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Matthew Avrillio ',
                    'nim' =>  '2501996902',
                    'email' => 'mattavrillio@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'TAF',
                    'division' => 'Transportation, Accommodation & Food',
                    'password' => Hash::make("AEO.TAF2501996902"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Daniel Joshua',
                    'nim' =>  '2501962896',
                    'email' => 'nondandirawung@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'TS',
                    'division' => 'Technical Support',
                    'password' => Hash::make("AEO.TS2501962896"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Eleanor Susanto',
                    'nim' =>  '2540121871',
                    'email' => 'eleaonerelen03@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'MIT',
                    'department' => 'MIT & Registration',
                    'division_id' => 'NR',
                    'division' => 'National Registration',
                    'password' => Hash::make("AEO.NR2540121871"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Romington Hydro',
                    'nim' =>  '2540124974',
                    'email' => 'Romi7868@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'MIT',
                    'department' => 'MIT & Registration',
                    'division_id' => 'IR',
                    'division' => 'International Registration',
                    'password' => Hash::make("AEO.IR2540124974"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Katryn Tania Tannady',
                    'nim' =>  '2501992785',
                    'email' => 'katryntaniatannady@gmail.com',
                    'position_id' => 2,
                    'position' => 'Director',
                    'department_id' => 'BR',
                    'department' => 'Branding',
                    'division_id' => 'BD',
                    'division' => 'Branding',
                    'password' => Hash::make("AEO.BD2501992785"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Michael Alexander',
                    'nim' =>  '2501961382',
                    'email' => 'mike.alex.lay@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'BR',
                    'department' => 'Branding',
                    'division_id' => 'DNP',
                    'division' => 'Design and Product',
                    'password' => Hash::make("AEO.DNP2501961382"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Muhammad Arif Nur Sidik',
                    'nim' =>  '2501965014',
                    'email' => 'muhammadarifns.14@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'BR',
                    'department' => 'Branding',
                    'division_id' => 'ESA',
                    'division' => 'External Support & Advertising',
                    'password' => Hash::make("AEO.ESA2501965014"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Aliya Salsiya Rahmania',
                    'nim' =>  '2502005452',
                    'email' => 'dumpemailaya@gmail.com',
                    'position_id' => 2,
                    'position' => 'Director',
                    'department_id' => 'FD',
                    'department' => 'Funding',
                    'division_id' => 'FD',
                    'division' => 'Funding',
                    'password' => Hash::make("AEO.FD2502005452"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Divany Nirwana Harudi',
                    'nim' =>  '2502045121',
                    'email' => 'divanynharudi@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'FD',
                    'department' => 'Funding',
                    'division_id' => 'FR',
                    'division' => 'Fundraising',
                    'password' => Hash::make("AEO.FR2502045121"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Alvina',
                    'nim' =>  '2501978396',
                    'email' => 'fualvina@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'FD',
                    'department' => 'Funding',
                    'division_id' => 'SS',
                    'division' => 'Sponsorship',
                    'password' => Hash::make("AEO.SS2501978396"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Jovic Wu',
                    'nim' =>  '2602097712',
                    'email' => 'jovicwu31@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'SB',
                    'division' => 'Spelling Bee',
                    'password' => Hash::make("AEO.SB2602097712"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Jason Satria Mudali',
                    'nim' =>  '2602103545',
                    'email' => 'jasonmudali0111@gmail.com ',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'SB',
                    'division' => 'Spelling Bee',
                    'password' => Hash::make("AEO.SB2602103545"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Jennifer Brigitta Trisulo',
                    'nim' =>  '2602196763',
                    'email' => 'Jennifertrisulo@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'SB',
                    'division' => 'Spelling Bee',
                    'password' => Hash::make("AEO.SB2602196763"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Sashi Karina',
                    'nim' =>  '2602205042',
                    'email' => 'sashi.karina04@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'NC',
                    'division' => 'Newscasting',
                    'password' => Hash::make("AEO.NC2602205042"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Muhammad Hafidz',
                    'nim' =>  '2602104592',
                    'email' => 'Muhammad.hafidz.220604@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'NC',
                    'division' => 'Newscasting',
                    'password' => Hash::make("AEO.NC2602104592"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Nadya Putri Rahmanita Achiral',
                    'nim' =>  '2502043766',
                    'email' => 'nadyapr2003@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'ST',
                    'division' => 'Storytelling',
                    'password' => Hash::make("AEO.ST2502043766"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Muchsin Alwi',
                    'nim' =>  '2602173816',
                    'email' => 'muchsinalwi4@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'ST',
                    'division' => 'Storytelling',
                    'password' => Hash::make("AEO.ST2602173816"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Ivan Rizky Sasongko',
                    'nim' =>  '2540124293',
                    'email' => 'ivanrizkysasongko@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'DB',
                    'division' => 'Debate',
                    'password' => Hash::make("AEO.DB2540124293"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Michael Simaela Tarima',
                    'nim' =>  '2502071100',
                    'email' => 'michaelsimaela922@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'DB',
                    'division' => 'Debate',
                    'password' => Hash::make("AEO.DB2502071100"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Teresa Stefanie Sheryl',
                    'nim' =>  '2602060035',
                    'email' => 'stefsheryl@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'DB',
                    'division' => 'Debate',
                    'password' => Hash::make("AEO.DB2602060035"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Ekanaka Hasudungan Pratama',
                    'nim' =>  '2602169144',
                    'email' => 'ekanakapratama@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'SP',
                    'division' => 'Speech',
                    'password' => Hash::make("AEO.SP2602169144"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Ferry Rachman Kurniawan',
                    'nim' =>  '2602135401',
                    'email' => 'ferrysafer808@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'SP',
                    'division' => 'Speech',
                    'password' => Hash::make("AEO.SP2602135401"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Nasywa Axelia',
                    'nim' =>  '2501988440',
                    'email' => 'nashaxelia@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'OC',
                    'division' => 'Online Competition',
                    'password' => Hash::make("AEO.OC2501988440"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Alex Sandro Steven',
                    'nim' =>  '2602233651',
                    'email' => 'zzyyzyzy0220@gmail.com ',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'OC',
                    'division' => 'Online Competition',
                    'password' => Hash::make("AEO.OC2602233651"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Alyssa Dian Zulkifli',
                    'nim' =>  '2502015900',
                    'email' => 'alyssa.zulkifli@binus.ac.id',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'EV',
                    'department' => 'Event',
                    'division_id' => 'ME',
                    'division' => 'Main Event',
                    'password' => Hash::make("AEO.ME2502015900"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Khalisa Aurelie Navira',
                    'nim' =>  '2602193925',
                    'email' => 'khalisa.navira@binus.ac.id',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'EV',
                    'department' => 'Event',
                    'division_id' => 'ME',
                    'division' => 'Main Event',
                    'password' => Hash::make("AEO.ME2602193925"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Khaira rahma Diandra',
                    'nim' =>  '2602249095',
                    'email' => 'khaira.rahma@gmail.com',
                    'position_id' => 4,
                    'position' => 'Senior Staff',
                    'department_id' => 'EV',
                    'department' => 'Event',
                    'division_id' => 'PE',
                    'division' => 'Party Event',
                    'password' => Hash::make("AEO.PE2602249095"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Bryan Limios',
                    'nim' =>  '2602060003',
                    'email' => 'bryanlimios08@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'EV',
                    'department' => 'Event',
                    'division_id' => 'PE',
                    'division' => 'Party Event',
                    'password' => Hash::make("AEO.PE2602060003"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Nicholas',
                    'nim' =>  '2602129802',
                    'email' => 'nicholaszhang23@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'EV',
                    'department' => 'Event',
                    'division_id' => 'PE',
                    'division' => 'Party Event',
                    'password' => Hash::make("AEO.PE2602129802"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Trista Sarah Ardine Nugroho',
                    'nim' =>  '2501979373',
                    'email' => 'tristaardine@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'ORD',
                    'division' => 'Officer Recruitment and Development',
                    'password' => Hash::make("AEO.ORD2501979373"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Wina Cendra',
                    'nim' =>  '2401962390',
                    'email' => 'wina0234@gmail.com',
                    'position_id' => 4,
                    'position' => 'Senior Staff',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'ORD',
                    'division' => 'Officer Recruitment and Development',
                    'password' => Hash::make("AEO.ORD2401962390"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Alicia Laurence',
                    'nim' =>  '2501976970',
                    'email' => 'alicia.chen230@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'ORD',
                    'division' => 'Officer Recruitment and Development',
                    'password' => Hash::make("AEO.ORD2501976970"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Nicholas Irvin Suhendi',
                    'nim' =>  '2602084956',
                    'email' => 'nicholasirvin123@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'TAF',
                    'division' => 'Transportation, Accommodation & Food',
                    'password' => Hash::make("AEO.TAF2602084956"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Jennifer Limardi',
                    'nim' =>  '2502000754',
                    'email' => 'jenniferlimardi3010@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'TAF',
                    'division' => 'Transportation, Accommodation & Food',
                    'password' => Hash::make("AEO.TAF2502000754"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Irsyad Nuryatama',
                    'nim' =>  '2502037795',
                    'email' => 'irsyad.nuryatama71@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'TS',
                    'division' => 'Technical Support',
                    'password' => Hash::make("AEO.TS2502037795"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Evan Somangkey',
                    'nim' =>  '2602070093',
                    'email' => 'evansomangkey03@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'LOG',
                    'department' => 'Logistic Department',
                    'division_id' => 'TS',
                    'division' => 'Technical Support',
                    'password' => Hash::make("AEO.TS2602070093"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Stefan Bondito',
                    'nim' =>  '2540122041',
                    'email' => 'stefanbondito@gmail.com',
                    'position_id' => 4,
                    'position' => 'Senior Staff',
                    'department_id' => 'MITR',
                    'department' => 'MIT & Registration',
                    'division_id' => 'MIT',
                    'division' => 'Media Information and Technology',
                    'password' => Hash::make("AEO.MIT2540122041")
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Okky Pratama',
                    'nim' =>  '2440077062',
                    'email' => 'okky3100@gmail.com',
                    'position_id' => 4,
                    'position' => 'Senior Staff',
                    'department_id' => 'MITR',
                    'department' => 'MIT & Registration',
                    'division_id' => 'MIT',
                    'division' => 'Media Information and Technology',
                    'password' => Hash::make("AEO.MIT2440077062")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Muhammad Keinanthan Wahyuwardhana',
                    'nim' =>  '2602083291',
                    'email' => 'keinan.wardhana@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'MITR',
                    'department' => 'MIT & Registration',
                    'division_id' => 'NR',
                    'division' => 'National Registration',
                    'password' => Hash::make("AEO.NR2602083291"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Andru Hafiz',
                    'nim' =>  '2602175172',
                    'email' => 'Andru22permana@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'MITR',
                    'department' => 'MIT & Registration',
                    'division_id' => 'NR',
                    'division' => 'National Registration',
                    'password' => Hash::make("AEO.NR2602175172"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Gabriella Saputra Suntara',
                    'nim' =>  '2502022206',
                    'email' => 'gabriellaasptra@gmail.com',
                    'position_id' => 4,
                    'position' => 'Senior Staff',
                    'department_id' => 'MITR',
                    'department' => 'MIT & Registration',
                    'division_id' => 'NR',
                    'division' => 'National Registration',
                    'password' => Hash::make("AEO.NR2502022206"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Masika Hermawan',
                    'nim' =>  '2602199903',
                    'email' => 'chikabutchic@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'MITR',
                    'department' => 'MIT & Registration',
                    'division_id' => 'IR',
                    'division' => 'International Registration',
                    'password' => Hash::make("AEO.IR2602199903"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Thaddeus Kendrick Andrian',
                    'nim' =>  '2602207054',
                    'email' => 'thaddeusandrian@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'MITR',
                    'department' => 'MIT & Registration',
                    'division_id' => 'IR',
                    'division' => 'International Registration',
                    'password' => Hash::make("AEO.IR2602207054"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Edison Valentino',
                    'nim' =>  '2440028092',
                    'email' => 'edisonvalentino2002@gmail.com',
                    'position_id' => 4,
                    'position' => 'Senior Staff',
                    'department_id' => 'MITR',
                    'department' => 'MIT & Registration',
                    'division_id' => 'IR',
                    'division' => 'International Registration',
                    'password' => Hash::make("AEO.IR2440028092"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Azra Andhika',
                    'nim' =>  '2501975255',
                    'email' => 'azrandhika@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'BR',
                    'department' => 'Branding',
                    'division_id' => 'ESA',
                    'division' => 'External Support & Advertising',
                    'password' => Hash::make("AEO.ESA2501975255"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Jacqueline Season',
                    'nim' =>  '2602079474',
                    'email' => 'jacquelineseason@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'BR',
                    'department' => 'Branding',
                    'division_id' => 'ESA',
                    'division' => 'External Support & Advertising',
                    'password' => Hash::make("AEO.ESA2602079474"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Jefta Yonathan Timotius',
                    'nim' =>  '2440043010',
                    'email' => 'jeftayonathan23@gmail.com',
                    'position_id' => 4,
                    'position' => 'Senior Staff',
                    'department_id' => 'BR',
                    'department' => 'Branding',
                    'division_id' => 'ESA',
                    'division' => 'External Support & Advertising',
                    'password' => Hash::make("AEO.ESA2440043010"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Jessica Gladis',
                    'nim' =>  '2602160593',
                    'email' => 'jessica.gladis@binus.ac.id',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'FD',
                    'department' => 'Funding',
                    'division_id' => 'FR',
                    'division' => 'Fundraising',
                    'password' => Hash::make("AEO.FR2602160593"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Livia Jonea Lunardi',
                    'nim' =>  '2602090965',
                    'email' => 'jonealunardilivia@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'FD',
                    'department' => 'Funding',
                    'division_id' => 'FR',
                    'division' => 'Fundraising',
                    'password' => Hash::make("AEO.FR2602090965"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Kelly Hermanto',
                    'nim' =>  '2602052191',
                    'email' => 'kellyhermanto89@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'FD',
                    'department' => 'Funding',
                    'division_id' => 'FR',
                    'division' => 'Fundraising',
                    'password' => Hash::make("AEO.FR2602052191"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Theresia Sandra Ameli Sigalingging',
                    'nim' =>  '2602117815',
                    'email' => 'theresiasigalingging544@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'FD',
                    'department' => 'Funding',
                    'division_id' => 'SS',
                    'division' => 'Sponsorship',
                    'password' => Hash::make("AEO.SS2602117815"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Elsye Amanda Putri Hutagaol',
                    'nim' =>  '2602147540',
                    'email' => 'amandaphgl@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'FD',
                    'department' => 'Funding',
                    'division_id' => 'SS',
                    'division' => 'Sponsorship',
                    'password' => Hash::make("AEO.SS2602147540"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Ryan Efendy',
                    'nim' =>  '2602127482',
                    'email' => 'ryaneffendy1212@gmail.com',
                    'position_id' => 5,
                    'position' => 'Staff',
                    'department_id' => 'FD',
                    'department' => 'Funding',
                    'division_id' => 'SS',
                    'division' => 'Sponsorship',
                    'password' => Hash::make("AEO.SS2602127482"),
                ],
                
                
            ]
        );
    }
}
