<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AdminSeeder extends Seeder
{

    public function run()
    {

        DB::table('admins')->insert(
            [
                [
                    'created_by' => 'admin',
                    'name' =>  'Michelle Natasya Subairi',
                    'nim' =>  '2540123795',
                    'email' => 'michelle.natasya12@gmail.com',
                    'position_id' => 1,
                    'position' => 'Project Manager',
                    'department_id' => 'SC',
                    'department' => 'Steering Committee',
                    'division_id' => 'PM',
                    'division' => 'Project Manager',
                    'password' => Hash::make("AEO.PM2540123795")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Geren Widiarta',
                    'nim' =>  '2540125030',
                    'email' => 'gerenwidiarta477@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'MIT',
                    'department' => 'MIT & Registration',
                    'division_id' => 'MIT',
                    'division' => 'Media Information and Technology',
                    'password' => Hash::make("AEO.MIT2540125030")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Stefan Bondito',
                    'nim' =>  '2540122041',
                    'email' => 'stefanbondito@gmail.com',
                    'position_id' => 2,
                    'position' => 'Staff',
                    'department_id' => 'MIT',
                    'department' => 'MIT & Registration',
                    'division_id' => 'MIT',
                    'division' => 'Media Information and Technology',
                    'password' => Hash::make("AEO.MIT2540122041")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Jose Stephen Satrya',
                    'nim' =>  '2540124551',
                    'email' => 'jose.satrya@gmail.com',
                    'position_id' => 2,
                    'position' => 'Director',
                    'department_id' => 'MIT',
                    'department' => 'MIT & Registration',
                    'division_id' => 'MIT',
                    'division' => 'MIT & Registration',
                    'password' => Hash::make("AEO.MIT2540122041")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Nicholas Frederick Oongwidjaja',
                    'nim' =>  '2501987192',
                    'email' => 'nicholas22oongwidjaja@gmail.com',
                    'position_id' => 1,
                    'position' => 'Vice Project Manager of Marketing',
                    'department_id' => 'SC',
                    'department' => 'Steering Committee',
                    'division_id' => 'VPMM',
                    'division' => 'Vice Project Manager of Marketing',
                    'password' => Hash::make("AEO.VPMM2501987192")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Stephany Angela Putri Langi',
                    'nim' =>  '2501999545',
                    'email' => 'langiwurangian@gmail.com',
                    'position_id' => 1,
                    'position' => 'Vice Project Manager of Operations',
                    'department_id' => 'SC',
                    'department' => 'Steering Committee',
                    'division_id' => 'VPMO',
                    'division' => 'Vice Project Manager of Operations',
                    'password' => Hash::make("AEO.VPMO2501999545")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Rahmadira Febi Herdiningtyas',
                    'nim' =>  '2540131456',
                    'email' => 'rahmadirafebih@gmail.com',
                    'position_id' => 1,
                    'position' => 'Secretary and Treasurer',
                    'department_id' => 'SC',
                    'department' => 'Steering Committee',
                    'division_id' => 'ST',
                    'division' => 'Secretary and Treasurer',
                    'password' => Hash::make("AEO.ST2540131456")
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Fanes Hanestan',
                    'nim' =>  '2502000193',
                    'email' => 'fanestan271203@gmail.com',
                    'position_id' => 2,
                    'position' => 'Director',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'CD',
                    'division' => 'Competition',
                    'password' => Hash::make("AEO.CD2502000193"),
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Joey Soesilo',
                    'nim' =>  '2540120351',
                    'email' => 'jsoesilo28@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'CP',
                    'department' => 'Competition',
                    'division_id' => 'OC',
                    'division' => 'Online Competition',
                    'password' => Hash::make("AEO.OC2540120351"),
                ],

                [
                    'created_by' => 'admin',
                    'name' =>  'Timotius Rosevalt',
                    'nim' =>  '2501961294',
                    'email' => 'timotiusrosevalt@gmail.com',
                    'position_id' => 2,
                    'position' => 'Director',
                    'department_id' => 'EV',
                    'department' => 'Event',
                    'division_id' => 'EV',
                    'division' => 'Event',
                    'password' => Hash::make("AEO.EV2501961294"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Gracia Nurmala',
                    'nim' =>  '2502050153',
                    'email' => 'graciaans@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'EV',
                    'department' => 'Event',
                    'division_id' => 'ME',
                    'division' => 'Main Event',
                    'password' => Hash::make("AEO.ME2502050153"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Kalvin Eryadi',
                    'nim' =>  '2540119734',
                    'email' => 'kalvineryadi12@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'EV',
                    'department' => 'Event',
                    'division_id' => 'PE',
                    'division' => 'Party Event',
                    'password' => Hash::make("AEO.PE2540119734"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Liesa Aprilianty',
                    'nim' =>  '2540124330',
                    'email' => 'liesaprilianty@gmail.com',
                    'position_id' => 2,
                    'position' => 'Director',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'LG',
                    'division' => 'Logistic',
                    'password' => Hash::make("AEO.LG2540124330"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Selma Andjani Mahanum',
                    'nim' =>  '2502011083',
                    'email' => 'andjani.sm@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'ORD',
                    'division' => 'Officer Recruitment and Development',
                    'password' => Hash::make("AEO.ORD2502011083"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Matthew Avrillio ',
                    'nim' =>  '2501996902',
                    'email' => 'mattavrillio@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'TAF',
                    'division' => 'Transportation, Accommodation & Food',
                    'password' => Hash::make("AEO.TAF2501996902"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Daniel Joshua',
                    'nim' =>  '2501962896',
                    'email' => 'nondandirawung@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'LOG',
                    'department' => 'Logistic',
                    'division_id' => 'TS',
                    'division' => 'Technical Support',
                    'password' => Hash::make("AEO.TS2501962896"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Eleanor Susanto',
                    'nim' =>  '2540121871',
                    'email' => 'eleaonerelen03@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'MIT',
                    'department' => 'MIT & Registration',
                    'division_id' => 'NR',
                    'division' => 'National Registration',
                    'password' => Hash::make("AEO.NR2540121871"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Romington Hydro',
                    'nim' =>  '2540124974',
                    'email' => 'Romi7868@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'MIT',
                    'department' => 'MIT & Registration',
                    'division_id' => 'IR',
                    'division' => 'International Registration',
                    'password' => Hash::make("AEO.IR2540124974"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Katryn Tania Tannady',
                    'nim' =>  '2501992785',
                    'email' => 'katryntaniatannady@gmail.com',
                    'position_id' => 2,
                    'position' => 'Director',
                    'department_id' => 'BR',
                    'department' => 'Branding',
                    'division_id' => 'BD',
                    'division' => 'Branding',
                    'password' => Hash::make("AEO.BD2501992785"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Michael Alexander',
                    'nim' =>  '2501961382',
                    'email' => 'mike.alex.lay@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'BR',
                    'department' => 'Branding',
                    'division_id' => 'DNP',
                    'division' => 'Design and Product',
                    'password' => Hash::make("AEO.DNP2501961382"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Muhammad Arif Nur Sidik',
                    'nim' =>  '2501965014',
                    'email' => 'muhammadarifns.14@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'BR',
                    'department' => 'Branding',
                    'division_id' => 'ESA',
                    'division' => 'External Support & Advertising',
                    'password' => Hash::make("AEO.ESA2501965014"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Aliya Salsiya Rahmania',
                    'nim' =>  '2502005452',
                    'email' => 'dumpemailaya@gmail.com',
                    'position_id' => 2,
                    'position' => 'Director',
                    'department_id' => 'FD',
                    'department' => 'Funding',
                    'division_id' => 'FD',
                    'division' => 'Funding',
                    'password' => Hash::make("AEO.FD2502005452"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Divany Nirwana Harudi',
                    'nim' =>  '2502045121',
                    'email' => 'divanynharudi@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'FD',
                    'department' => 'Funding',
                    'division_id' => 'FR',
                    'division' => 'Fundraising',
                    'password' => Hash::make("AEO.FR2502045121"),
                ],
                [
                    'created_by' => 'admin',
                    'name' =>  'Alvina',
                    'nim' =>  '2501978396',
                    'email' => 'fualvina@gmail.com',
                    'position_id' => 3,
                    'position' => 'Coordinator',
                    'department_id' => 'FD',
                    'department' => 'Funding',
                    'division_id' => 'SP',
                    'division' => 'Sponsorship',
                    'password' => Hash::make("AEO.SP2501978396"),
                ],
                
            ]
        );
    }
}
